name: vibration
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password 
    networks:
      - vibration-network

  # backend:
  #   build:
  #     context: ../backend
  #     dockerfile: Dockerfile
  #   container_name: backend
  #   environment:
  #     DB_HOST: mysql
  #     DB_PORT: 3306
  #     DB_USERNAME: root
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_DATABASE: ${DB_DATABASE}
  #   depends_on:
  #     - mysql
  #   networks:
  #     - vibration-network

  # frontend:
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   restart: unless-stopped
  #   depends_on:
  #     - backend
  #   networks:
  #     - vibration-network

volumes:
  mysql_data:

networks:
  vibration-network:
    driver: bridge